version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 5001:5001
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: secreta
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: